export type Branch = 'A' | 'B' | 'C' | 'D'

export type SituationId =
  | 'work-career'
  | 'relationship'
  | 'family'
  | 'money'
  | 'big-decision'
  | 'my-health'
  | 'who-i-am'
  | 'loss-grief'
  | 'anxiety'
  | 'life-change'
  | 'friendship'
  | 'not-sure'
export type PlanTier = 'free' | 'essentials' | 'insights'
export type SubscriptionStatus = 'active' | 'canceled' | 'past_due' | 'unpaid' | 'trialing'
export type Season = 'W' | 'Sp' | 'Su' | 'Au'
export type ResonanceTap = 'accurate' | 'not_quite'
export type FlagType = 'suicidal_ideation' | 'self_harm' | 'harm_to_others' | 'acute_crisis'

export interface SafetyResult {
  flagged: boolean
  flagType: FlagType | null
  confidence: number
}

export interface MirrorOutput {
  carrying: string
  underneath: string
  question: string
  /**
   * A short, third-person paraphrase of what the person was carrying —
   * e.g. "a tension between staying and leaving a long-held role."
   * Generated by the Mirror at session-completion time, stored encrypted
   * (AES-256-GCM, session_content.encrypted_memory_note), and used only to
   * seed a future "welcome back" greeting / check-in email. Never shown
   * within the session it was generated in, never populated when
   * safetyFlagged is true, and never a verbatim quote of the user's words
   * (same anchoring-without-quoting principle as `carrying`).
   */
  memoryNote: string
  season: Season
  patternTags: string[]
  safetyFlagged: boolean
  promptVersion: string
}

export interface SessionState {
  sessionId?: string
  branch?: Branch
  emotionTags: string[]
  intensity?: number
  contextText?: string
  mirrorOutput?: MirrorOutput
  resonanceTap?: ResonanceTap
  safetyFlagged: boolean
}

export interface EventPayload {
  /** Omitted for events fired before a sessions row exists (e.g. anonymous flow). */
  sessionId?: string
  eventName: string
  properties?: Record<string, unknown>
}

// ── Beta feedback ─────────────────────────────────────────────────────────────

export type FeedbackRating    = 1 | 2 | 3 | 4 | 5
export type FeedbackFrequency = 'first_time' | 'few_times' | 'weekly' | 'daily_or_more'
export type FeedbackEase      = 'very_difficult' | 'difficult' | 'neutral' | 'easy' | 'very_easy'
export type FeedbackRecommend = 'yes_already' | 'yes_likely' | 'maybe' | 'not_yet'

export interface FeedbackPayload {
  overall_rating:   FeedbackRating | null
  use_frequency:    FeedbackFrequency | null
  most_valuable:    string[]
  ease_of_use:      FeedbackEase | null
  improvements:     string[]
  would_recommend:  FeedbackRecommend | null
  comments:         string
}

export interface FeedbackRow extends FeedbackPayload {
  id:         string
  user_id:    string
  created_at: string
}

// ── Events ────────────────────────────────────────────────────────────────────

export type EventName =
  | 'session_start'
  | 'branch_selected'
  | 'emotions_submitted'
  | 'intensity_submitted'
  | 'context_submitted'
  | 'mirror_rendered'
  | 'resonance_tapped'
  | 'season_shown'
  | 'nextstep_selected'
  | 'session_complete'
  | 'safety_event'
  | 'session_drop'
