import { LegalLayout } from '@/components/ui/LegalLayout'

export const metadata = {
  title: 'Terms of Use — Soul Space',
  description: 'The terms and conditions for using Soul Space.',
}

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Use"
      subtitle="Please read these terms before using Soul Space."
      lastUpdated="May 2026"
      sections={[
        {
          heading: '1. What Soul Space Is — and Is Not',
          body: (
            <div className="space-y-2">
              <p>
                Soul Space is a guided emotional reflection tool. It is designed to help you
                pause, articulate what you are feeling, and receive a non-judgmental reflection
                of what seems to be present.
              </p>
              <p><strong className="text-sand">Soul Space is not:</strong></p>
              <ul className="list-disc list-inside space-y-1 mt-1">
                <li>A therapy service or substitute for professional mental health care</li>
                <li>A medical device or diagnostic tool</li>
                <li>A crisis service or emergency resource</li>
                <li>A chatbot or conversational AI companion</li>
              </ul>
              <p className="mt-2">
                If you are in immediate distress or danger, please call or text <strong className="text-sand">988</strong> (Suicide &amp; Crisis Lifeline, US) or contact your local emergency services.
              </p>
            </div>
          ),
        },
        {
          heading: '2. Eligibility',
          body: (
            <p>
              You must be at least 13 years old to use Soul Space. By using the service, you
              confirm that you meet this requirement. If you are under 18, you represent that
              a parent or guardian has reviewed and agreed to these terms on your behalf.
            </p>
          ),
        },
        {
          heading: '3. Your Account',
          body: (
            <div className="space-y-2">
              <p>
                You may use Soul Space anonymously (without an account) for a limited number of
                sessions. To save sessions and access your history, you must create an account
                using your email address.
              </p>
              <p>
                You are responsible for keeping your email address current and for any activity
                under your account. Magic links expire after one hour and are single-use.
              </p>
              <p>
                You may delete your account at any time from your settings page. Deletion removes
                your personal information and all associated session data permanently.
              </p>
            </div>
          ),
        },
        {
          heading: '4. Subscriptions and Payments',
          body: (
            <div className="space-y-2">
              <p>
                Some features of Soul Space require a paid subscription (&ldquo;Essentials&rdquo; or
                &ldquo;Insights&rdquo; plans). Subscriptions are billed on a monthly basis and renew
                automatically until cancelled.
              </p>
              <p>
                Payments are processed by Stripe. By subscribing, you agree to Stripe&rsquo;s{' '}
                <a href="https://stripe.com/legal/ssa" target="_blank" rel="noopener noreferrer" className="underline hover:opacity-80">
                  Terms of Service
                </a>. We do not store your payment card information.
              </p>
              <p>
                You may cancel your subscription at any time from your account settings. Access
                continues through the end of the current billing period. No partial refunds are
                provided for unused time, except where required by applicable law.
              </p>
            </div>
          ),
        },
        {
          heading: '5. Acceptable Use',
          body: (
            <div className="space-y-2">
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-1 mt-1">
                <li>Use Soul Space to harm yourself or others</li>
                <li>Attempt to extract, reverse-engineer, or reproduce the Mirror AI prompts or system design</li>
                <li>Use automated tools to access or scrape Soul Space in bulk</li>
                <li>Impersonate another person or provide false information</li>
                <li>Use Soul Space in any way that violates applicable law</li>
              </ul>
            </div>
          ),
        },
        {
          heading: '6. AI-Generated Content',
          body: (
            <div className="space-y-2">
              <p>
                The Mirror reflection you receive is generated by an AI model (Anthropic Claude)
                based on what you share. It is descriptive, not diagnostic. It reflects patterns
                in language — it does not assess your mental health, predict behaviour, or provide
                medical or therapeutic advice.
              </p>
              <p>
                AI outputs can be imperfect, incomplete, or occasionally inaccurate. You should
                never make significant personal, medical, or legal decisions based solely on a
                Mirror reflection.
              </p>
            </div>
          ),
        },
        {
          heading: '7. Intellectual Property',
          body: (
            <p>
              Soul Space, its design, AI prompts, copy, and software are the intellectual
              property of Soul Space Health, Inc. You may not reproduce, distribute, or create
              derivative works from any part of Soul Space without our written permission.
              Your session content belongs to you.
            </p>
          ),
        },
        {
          heading: '8. Disclaimers',
          body: (
            <div className="space-y-2">
              <p>
                Soul Space is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
                warranties of any kind. We do not warrant that the service will be uninterrupted,
                error-free, or that AI outputs will meet your expectations.
              </p>
              <p>
                To the maximum extent permitted by law, Soul Space Health, Inc. is not liable
                for any indirect, incidental, special, or consequential damages arising from
                your use of Soul Space, including any reliance on Mirror reflections.
              </p>
            </div>
          ),
        },
        {
          heading: '9. Changes to These Terms',
          body: (
            <p>
              We may update these terms from time to time. We will notify you by email of
              material changes at least 14 days before they take effect. Continued use of
              Soul Space after changes take effect constitutes your acceptance of the updated terms.
            </p>
          ),
        },
        {
          heading: '10. Governing Law',
          body: (
            <p>
              These terms are governed by the laws of the State of Delaware, United States,
              without regard to conflict of law principles. Any disputes shall be resolved
              in the courts of Delaware.
            </p>
          ),
        },
        {
          heading: '11. Contact',
          body: (
            <p>
              Questions about these terms can be sent to{' '}
              <a href="mailto:legal@soulspacehealth.org" className="underline hover:opacity-80">
                legal@soulspacehealth.org
              </a>.
            </p>
          ),
        },
      ]}
    />
  )
}
