-- Soul Space — Memory & gentle check-ins (Phase 2 retention build)
-- Safe to run multiple times (idempotent).
-- Run in Supabase Dashboard → SQL Editor for each environment (Dev, QA, Prod).
--
-- Beta research (2 rounds, convergent): the #1 named reason people would
-- return is that the app remembers them and checks in gently. This migration
-- adds the minimal storage needed for both:
--
--   1. session_content.encrypted_memory_note
--      A short, ENCRYPTED (AES-256-GCM, same as encrypted_context /
--      encrypted_mirror_output) one-line paraphrase of what the person was
--      carrying — generated by the Mirror at session-completion time.
--      It is narrative-derived (even paraphrased, it reflects what someone
--      wrote), so — unlike emotion_tags / season_assigned — it MUST be
--      encrypted at rest. It gets its own column (rather than living only
--      inside encrypted_mirror_output) so a future session's "welcome back"
--      greeting can fetch one short field without decrypting the full
--      mirror blob (carrying + underneath + question) on every return visit.
--
--   2. users.check_in_frequency / users.last_check_in_sent_at
--      Mirrors the existing last_re_engagement_sent_at cooldown pattern
--      (see 010_email_tracking.sql) so the check-in feature reuses the
--      proven digest-cron + cooldown-stamp infrastructure rather than
--      inventing new send/suppression logic. Off by default — explicit
--      opt-in only, per the "gentle, never nagging" research finding.

alter table session_content
  add column if not exists encrypted_memory_note text;

alter table users
  add column if not exists check_in_frequency text not null default 'off'
    check (check_in_frequency in ('off', 'biweekly', 'monthly')),
  add column if not exists last_check_in_sent_at timestamptz;

comment on column session_content.encrypted_memory_note is
  'AES-256-GCM encrypted one-line paraphrase of the session, generated by the Mirror. Used to seed the next session''s "welcome back" greeting and check-in email copy. Never populated for safety_flagged sessions.';

comment on column users.check_in_frequency is
  'Opt-in cadence for gentle check-in emails: off (default) | biweekly | monthly. Never higher-frequency — the product enforces "gentle" by not offering anything tighter.';

comment on column users.last_check_in_sent_at is
  'Cooldown stamp mirroring last_re_engagement_sent_at — prevents the digest cron from sending check-ins more often than the user''s chosen cadence.';
